### ISSUE TITLE
FastOverflowPacketException error

### ISSUE THREAD

**Issue by Hikki8** [Dimatert9/BungeeCord#102]
Использую версию 3.8.9

Поставил плагин на очереди: https://www.spigotmc.org/resources/ajqueue.78266/ (Версия 2.2.2)

Получаю ошибку:

```
23:45:19 [SEVERE] Caused by: io.netty.handler.codec.DecoderException: ru.leymooo.botfilter.utils.FastOverflowPacketException: Packet #0 could not be framed because was too large (expected 1038 bytes, got 2486 bytes)

23:45:19 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:477)

23:45:19 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)

23:45:19 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

23:45:19 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

23:45:19 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

23:45:19 [SEVERE]     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)

23:45:19 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

23:45:19 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

23:45:19 [SEVERE]     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)

23:45:19 [SEVERE]     at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)

23:45:19 [SEVERE]     at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)

23:45:19 [SEVERE]     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)

23:45:19 [SEVERE]     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)

23:45:19 [SEVERE]     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

23:45:19 [SEVERE]     ... 1 more

23:45:19 [SEVERE] Caused by: ru.leymooo.botfilter.utils.FastOverflowPacketException: Packet #0 could not be framed because was too large (expected 1038 bytes, got 2486 bytes)
```

Отписал автору плагина - сказал на стороне прокси ошибка, это так?

**Comment by Leymooo** [comment]
Это точно полная ошибка?

**Comment by Hikki8** [comment]
Вот полный лог между сессиями дебаггера:
https://pastebin.com/cs086GUc

**Comment by Leymooo** [comment]
Попробуй эту версию https://github.com/Leymooo/BungeeCord/actions/runs/1658606206

**Comment by Hikki8** [comment]
В артефактах сборки скачиваемый файл судя по всему побит. После скачивания 1Кб весит.

**Comment by Leymooo** [comment]
https://github.com/Leymooo/BungeeCord/actions/runs/1659275806

**Comment by Hikki8** [comment]
Спасибо, всё работает
