### ISSUE TITLE
Не загружается конфиг + сама банжа

### ISSUE THREAD

**Issue by kazyavich** [Dimatert9/BungeeCord#131]
### Bungeecord version

3.8.12

### Client version

1.19.2

### Bungeecord plugins

AuthMeBungee 2.2.0 beta1
bungee_layer 1.1.0
CommandSync 2.8.2
LuckPerms Bungee 5.4.52
protocolize_bungeecord
SkinsRestorer
Yamler_Bungee 2.4.0

### The bug

13:35:50 [SEVERE] Exception in thread "main" 
13:35:50 [SEVERE] java.lang.reflect.InaccessibleObjectException: Unable to make private native java.lang.reflect.Field[] java.lang.Class.getDeclaredFields0(boolean) accessible: module java.base does not "opens java.lang" to unnamed module @62bd2070

13:35:50 [SEVERE]     at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)

13:35:50 [SEVERE]     at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)

13:35:50 [SEVERE]     at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)

13:35:50 [SEVERE]     at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)

13:35:50 [SEVERE]     at ru.leymooo.botfilter.config.Config.setAccessible(Config.java:371)

13:35:50 [SEVERE]     at ru.leymooo.botfilter.config.Config.getField(Config.java:258)

13:35:50 [SEVERE]     at ru.leymooo.botfilter.config.Config.set(Config.java:54)

13:35:50 [SEVERE]     at ru.leymooo.botfilter.config.Config.set(Config.java:114)

13:35:50 [SEVERE]     at ru.leymooo.botfilter.config.Config.load(Config.java:99)

13:35:50 [SEVERE]     at ru.leymooo.botfilter.config.Settings.reload(Settings.java:62)

13:35:50 [SEVERE]     at ru.leymooo.botfilter.BotFilter.<init>(BotFilter.java:74)

13:35:50 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:289)

13:35:50 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:49)

13:35:50 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

### Log output (links)

13:35:50 [SEVERE] Exception in thread "main" 
13:35:50 [SEVERE] java.lang.reflect.InaccessibleObjectException: Unable to make private native java.lang.reflect.Field[] java.lang.Class.getDeclaredFields0(boolean) accessible: module java.base does not "opens java.lang" to unnamed module @62bd2070

13:35:50 [SEVERE]     at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)

13:35:50 [SEVERE]     at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)

13:35:50 [SEVERE]     at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)

13:35:50 [SEVERE]     at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)

13:35:50 [SEVERE]     at ru.leymooo.botfilter.config.Config.setAccessible(Config.java:371)

13:35:50 [SEVERE]     at ru.leymooo.botfilter.config.Config.getField(Config.java:258)

13:35:50 [SEVERE]     at ru.leymooo.botfilter.config.Config.set(Config.java:54)

13:35:50 [SEVERE]     at ru.leymooo.botfilter.config.Config.set(Config.java:114)

13:35:50 [SEVERE]     at ru.leymooo.botfilter.config.Config.load(Config.java:99)

13:35:50 [SEVERE]     at ru.leymooo.botfilter.config.Settings.reload(Settings.java:62)

13:35:50 [SEVERE]     at ru.leymooo.botfilter.BotFilter.<init>(BotFilter.java:74)

13:35:50 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:289)

13:35:50 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:49)

13:35:50 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

### Checking

- [ ] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by NyashMyash99** [comment]
**Способ повторения ошибки**
На абсолютно чистой версии ( без изменений и плагинов ), достаточно сохранить `BotFilter/config.yml`.

Даже если контент файла остаётся тем же - появляется ошибка ( проверял на NotePad++ и обычном Блокноте ).

**Comment by NyashMyash99** [comment]
#90

**Comment by Kupers** [comment]
Первый запуск происходит нормально, после создания папки BotFilter повторный запуск вызывает ошибку, если удалить папку BotFilter то сервер запустится
The first launch is normal, after creating the botfilter folder, the second launch causes an error, if you delete the botfilter folder, the server will start

3.8.13 
java version "17.0.1" 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)

Для запуска на новых версиях Java (Java 16+) добавьте эти флаги в строку запуска перед -jar (При ошибке java.lang.reflect.InaccessibleObjectException: Unable to make private native):
--illegal-access=permit (Java 16 и ниже)
или
--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED 

$ java --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED -Xms500M -Xms500M -jar -Dfile.encoding=UTF-8 BungeeCord.jar
$


**Это исправляет ситуацию**


22:35:20 [WARNING] Включаю BungeeCord BotFilter 1.8.x-1.20.x от vk.com/Leymooo_s (http://rubukkit.org/threads/137038)
22:35:20 [SEVERE] Exception in thread "main" 
22:35:20 [SEVERE] java.lang.reflect.InaccessibleObjectException: Unable to make private native java.lang.reflect.Field[] java.lang.Class.getDeclaredFields0(boolean) accessible: module java.base does not "opens java.lang" to unnamed module @7f416310

22:35:20 [SEVERE] 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)

22:35:20 [SEVERE] 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)

22:35:20 [SEVERE] 	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)

22:35:20 [SEVERE] 	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)

22:35:20 [SEVERE] 	at ru.leymooo.botfilter.config.Config.setAccessible(Config.java:371)

22:35:20 [SEVERE] 	at ru.leymooo.botfilter.config.Config.getField(Config.java:258)

22:35:20 [SEVERE] 	at ru.leymooo.botfilter.config.Config.set(Config.java:54)

22:35:20 [SEVERE] 	at ru.leymooo.botfilter.config.Config.set(Config.java:114)

22:35:20 [SEVERE] 	at ru.leymooo.botfilter.config.Config.load(Config.java:99)

22:35:20 [SEVERE] 	at ru.leymooo.botfilter.config.Settings.reload(Settings.java:62)

22:35:20 [SEVERE] 	at ru.leymooo.botfilter.BotFilter.<init>(BotFilter.java:74)

22:35:20 [SEVERE] 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:289)

22:35:20 [SEVERE] 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:49)

22:35:20 [SEVERE] 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
