### ISSUE TITLE
Не может прогрузить сервер после настройки   mode: 2 на 67 строке

### ISSUE THREAD

**Issue by meshoksnega** [Dimatert9/BungeeCord#136]
### Bungeecord version

BungeeCord-BotFilter-3.8.13.jar

### Server version

Spigot

### Client version

1.20.1

### Bungeecord plugins

BungeeGuard
![image](https://github.com/Leymooo/BungeeCord/assets/70194485/4948d430-97dd-47bf-b3c7-e3643f81942e)

### The bug

После того как я настроил на строке 67, всё перестало работать, и сервер не запускался

### Log output (links)

05:39:32 [SEVERE] Exception in thread "main" 
05:39:32 [SEVERE] while parsing a block mapping
 in 'reader', line 2, column 1:
    issues: "https://github.com/Leym ... 
    ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 67, column 3:
      mode: 2
      ^
05:52:56 [SEVERE] 	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:679)

05:52:56 [SEVERE] 	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:185)

05:52:56 [SEVERE] 	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:57)

05:52:56 [SEVERE] 	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:43)

05:52:56 [SEVERE] 	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:136)

05:52:56 [SEVERE] 	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:116)

05:52:56 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:239)

05:52:56 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:208)

05:52:56 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:357)

05:52:56 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:336)

05:52:56 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:311)

05:52:56 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:212)

05:52:56 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:134)

05:52:56 [SEVERE] 	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:160)

05:52:56 [SEVERE] 	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:184)

05:52:56 [SEVERE] 	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:477)

05:52:56 [SEVERE] 	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:443)

05:52:56 [SEVERE] 	at net.md_5.bungee.config.YamlConfiguration.load(YamlConfiguration.java:94)

05:52:56 [SEVERE] 	at net.md_5.bungee.config.YamlConfiguration.load(YamlConfiguration.java:87)

05:52:56 [SEVERE] 	at ru.leymooo.botfilter.config.Config.load(Config.java:92)

05:52:56 [SEVERE] 	at ru.leymooo.botfilter.config.Settings.reload(Settings.java:62)

05:52:56 [SEVERE] 	at ru.leymooo.botfilter.BotFilter.<init>(BotFilter.java:74)

05:52:56 [SEVERE] 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:289)

05:52:56 [SEVERE] 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:49)

05:52:56 [SEVERE] 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by andreasdc** [comment]
You did a mistake with your config probably.
